# Generated by Django 5.1.5 on 2025-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your phone number (e.g., +1234567890).', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_media',
            field=models.CharField(blank=True, help_text='Your social media handle (e.g., @username).', max_length=100, null=True),
        ),
    ]
