# Generated by Django 5.1.5 on 2025-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_phone_number_userprofile_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short introduction about yourself (max 500 characters).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload your profile picture.', null=True, upload_to='profile_images/'),
        ),
    ]
