# Generated by Django 5.1.5 on 2025-04-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_bio_alter_userprofile_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gmail',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
