# Generated by Django 5.1.5 on 2025-04-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gmail',
        ),
    ]
