# Generated by Django 5.1.5 on 2025-04-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_gmail'),
    ]

    operations = [
    ]
