# Generated by Django 5.0 on 2025-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20250417_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.CharField(choices=[('purple', 'Purple'), ('green', 'Green'), ('blue', 'Blue')], default='purple', max_length=10),
        ),
    ]
