# Generated by Django 5.0 on 2025-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_priority_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('fetched_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'unique_together': {('fetched_date',)},
            },
        ),
    ]
