# Generated by Django 5.1.6 on 2025-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_priority_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notify_before',
            field=models.IntegerField(blank=True, choices=[(5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (20, '20 minutes before'), (30, '30 minutes before')], help_text='Send notification this many minutes before start', null=True),
        ),
    ]
