# Generated by Django 5.2 on 2025-04-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_latitude_task_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latitude2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='longitude2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
