# Generated by Django 5.1.6 on 2025-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_due_date_task_notified_task_notify_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recur',
            field=models.CharField(choices=[('none', 'Do not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
