# Generated by Django 5.1.6 on 2025-04-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify_before',
            field=models.IntegerField(blank=True, choices=[(5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (20, '20 minutes before'), (30, '30 minutes before')], help_text='Send notification this many minutes before start', null=True),
        ),
    ]
