# Generated by Django 5.1.6 on 2025-04-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_quote'),
        ('tasks', '0004_task_recur'),
    ]

    operations = [
    ]
