# Generated by Django 5.1.6 on 2025-04-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
